kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
    templates:
    - '/etc/alertmanager/*.tmpl'

    route:
      receiver: alert-telegram
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: alert-telegram
          match:
            severity: telegram
          group_wait: 10s
          repeat_interval: 1m

    receivers:
    - name: alert-telegram
      telegram_configs:
      - bot_token: '8021960991:AAEKEa1YEnXvUOKDmeESke3bFLsICK-rZRM'  # Замініть на ваш токен бота
        chat_id: 804705806        # Замініть на ваш ID чату
        send_resolved: true              # Відправляти повідомлення про розв'язання алертів
